name: Build MiLightHub ESP32

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install PlatformIO
        run: pip install -U platformio
      - name: Build (esp32dev)
        run: pio run -e esp32dev
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: milight-hub-esp32dev
          path: .pio/build/esp32dev/firmware.bin

